name: Lint & Test Charts

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for helm-docs to detect changes

      - name: Install helm-docs
        run: |
          # Replace with your preferred installation method
          go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run helm-docs
        run: helm-docs --chart-search-root ./charts --dry-run # Use your chart directory

      - name: Verify no changes to docs # This is the enforcement step
        run: |
          git diff --exit-code -- ./**/README.md
          # You might need to adjust the path above depending on where helm-docs outputs files
          # and if you generate one README per chart or a global one.
          # For per-chart READMEs (default behavior):
          # find ./charts -name README.md -print0 | xargs -0 git diff --exit-code
          # If any README.md generated by helm-docs has changes, git diff will exit non-zero, failing the pipeline.
